# Copyright (C) 2024 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: GPL-3.0
#
# This library is free software: you can redistribute it and/or
# modify it under the terms of the GNU Public License as published
# by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Public License along
# with this library.  If not, see
# <https://www.gnu.org/licenses/>.

name: Run Codecov

on:
  push:
    branches: [ main ]
    paths:
      - ".github/.codecov.yml"
      - ".github/workflows/codecov.yml"
      - "cmake/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/.codecov.yml"
      - ".github/workflows/codecov.yml"
      - "cmake/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CCACHE_DIR: "/opt/ccache-cache"
  CCACHE_COMPILERCHECK: "content"
  CCACHE_COMPRESSLEVEL: "13"
  CCACHE_MAXSIZE: "200M"
  CONAN_HOME: "/opt/conan/"

jobs:
  run-codecov:
    name: Codecov
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-gcc-14
      options: '--user=root'

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Generate cache key
        id: cache-key
        run: |
          hash="${{ hashFiles('conanfile.py', '.github/workflows/codecov.yml') }}"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%s')"

          ccache_key_prefix="codecov-ccache-$hash"

          echo "conan-key=codecov-$hash" >> $GITHUB_OUTPUT
          echo "ccache-key=${ccache_key_prefix}-${current_date}" >> $GITHUB_OUTPUT
          echo "ccache-restore-key=$ccache_key_prefix" >> $GITHUB_OUTPUT

      - name: Restore Conan cache
        id: cache-conan
        uses: actions/cache/restore@v4
        with:
          key: conan-${{ steps.cache-key.outputs.conan-key }}
          path: ${{ env.CONAN_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source
          conan remove --confirm "*"

      - name: Copy Conan settings
        run: cp "/root/.conan2/settings.yml" "$CONAN_HOME"

      - name: Install build dependencies
        run: |
          conan install .                        \
             --build=missing                     \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH" \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH" \
             -s build_type=Debug                 \
             -s compiler.libcxx=libstdc++11      \
             -s compiler.cppstd=17               \
             --output-folder=build

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Save Conan cache
        uses: actions/cache/save@v4
        if: steps.cache-conan.outputs.cache-hit != 'true'
        with:
          key: conan-${{ steps.cache-key.outputs.conan-key }}
          path: ${{ env.CONAN_HOME }}

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug                      \
                -DCMAKE_PREFIX_PATH="$PWD/build"              \
                -DENABLE_DEVELOPER_MODE=ON                    \
                -DOPT_ENABLE_COVERAGE=ON                      \
                -DOPT_ENABLE_SANITIZER_ADDRESS=OFF            \
                -DOPT_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=OFF \
                -DOPT_ENABLE_CLANG_TIDY=OFF                   \
                -DNCHG_ENABLE_TESTING=ON                      \
                -S .                                          \
                -B build

      - name: Cache Ccache folder
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache-key.outputs.ccache-key }}
          restore-keys: ${{ steps.cache-key.outputs.ccache-restore-key }}
          path: ${{ env.CCACHE_DIR }}

      - name: Build project
        run: cmake --build build -j $(nproc)

      - name: Print Ccache statistics
        run: ccache -s

      - name: Run unit tests
        run: |
          ctest --test-dir build/   \
                --schedule-random   \
                --output-on-failure \
                --no-tests=error    \
                --timeout 90        \
                -j $(nproc) |&
          head -n 1000

      - name: Run integration tests
        run: |
          build/src/nchg/NCHG compute test/data/ENCFF447ERX.1000000.cool --threads "$(nproc)" out
          rm out*
          build/src/nchg/NCHG compute test/data/ENCFF447ERX.1000000.cool --cis-only --threads 1 out
          build/src/nchg/NCHG merge out out.parquet --threads "$(nproc)"
          build/src/nchg/NCHG filter out.parquet out.filtered.parquet --threads "$(nproc)"
          build/src/nchg/NCHG view out.parquet > /dev/null
          build/src/nchg/NCHG view out.filtered.parquet > /dev/null
          printf 'chr1\t0\t248956422' > mask.bed
          build/src/nchg/NCHG expected test/data/ENCFF447ERX.1000000.cool --output out.h5 --bin-mask  mask.bed

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          gcov: true
          gcov_executable: gcov-14
          os: linux
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true


  codecov-status-check:
    name: Status Check (Codecov)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - run-codecov

    steps:
      - name: Collect job results
        if: needs.run-codecov.result != 'success'
        run: exit 1
